### PR TITLE
Registers change APIs.

### PR DESCRIPTION
**Pull request by lab313ru**
Check it, please.

### CODE REVIEW

**Comment by lab313ru** [comment]
Don't sure about `Ppu.cpp` change. Don't know, how it appeared in my changes.

**Comment by lab313ru** [comment]
Should I resolve that conflict in `Ppu.cpp` so you'll have an ability to merge the PR?

**Comment by NovaSquirrel** [comment]
I got it, looks like the PPU changes _were_ supposed to be there so I put them back

**Comment by NovaSquirrel** [comment]
Thanks for your help, by the way!

**Comment by lab313ru** [comment]
Seems, you have the same ideas about this debugger:) Could I join your project, or should I continue doing changes in my fork? For me it would be better to work on your fork.

**Comment by lab313ru** [comment]
Thank you:)

**Pull request merged**
